[package]
name = "file-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.4"
clipboard-win = { version = "4.5.0", features = ["std"] }
crossterm = "0.26.1"
ctrlc = "3.4.0"
